#pragma once

enum VIEWTYPE
{
    VT_INVALID,
    VT_PERSPECTIVE,
    VT_LINEAR_DEPTH_NORMAL,
    VT_DUAL_PARABOLOID_ENVMAP,
    VT_GBUFFER,
    VT_LIGHTS,
    VT_FINALPASS,
    VT_SILHOUETTE,
    VT_NUM_VIEW_TYPES
};